### barplot_AUC_all_models_cohorts.R
###
### Author: Valeria Vitelli
### Contributers: Andrew Reiner, Alvaro Köhn-Luque
##
### Generates AUC barplots for all cohorts
###
### barplot_AUC_all_models_cohorts.R uses the results generated by
### validation_all_models.R and validation_code_London/validation_code.R
### The results from these scripts must be imported to spredsheets; see the
### provided spreadsheets for the required format, and the notes below.

library(readxl)
library(dplyr)

### load results for the Oslo cohort
###---------------------------------

AUCoslo <- matrix(NA, 4, 3)

# choose imputation method
impu.type <- 'single KNN'
which.impu.type <- c('single KNN', 'single RF', 'multi BR', 'multi GP')

### The xlsx files used here were created using the data from the tables
### named validation_plots_all_models/validation_*_table.txt

# read results
resXie <- read_excel('./validation_plots_all_models/validation_Xie_table.xlsx', 
                     sheet = match(impu.type, which.impu.type))
AUCoslo[1,] <- c(resXie$AUC, resXie$CI_AUC_low, resXie$CI_AUC_upp)
resZhangD <- read_excel('./validation_plots_all_models/validation_Zhang_death_table.xlsx', 
                        sheet = match(impu.type, which.impu.type))
AUCoslo[2,] <- c(resZhangD$AUC, resZhangD$CI_AUC_low, resZhangD$CI_AUC_upp)
resZhangP <- read_excel('./validation_plots_all_models/validation_Zhang_poor_outcome_table.xlsx', 
                        sheet = match(impu.type, which.impu.type))
AUCoslo[3,] <- c(resZhangP$AUC, resZhangP$CI_AUC_low, resZhangP$CI_AUC_upp)
resAll <- read_excel('./validation_plots_all_models/validation_Allenbach_table.xlsx', 
                     sheet = match(impu.type, which.impu.type))
AUCoslo[4,] <- c(resAll$AUC, resAll$CI_AUC_low, resAll$CI_AUC_upp)

row_names = c('Xie', 'Zhang1', 'Zhang2', 'Allenbach')
row.names(AUCoslo) <- row_names

### load results for the KCH cohort
###---------------------------------
###
### validation_table_KCH.xlsx was created from the data in
### validation_code_London/results/validation_*_table.txt

AUCkch <- matrix(NA, 4, 3)
resKCH <- read_excel('./validation_code_London/results/validation_table_KCH.xlsx')
AUCkch[,1] <- resKCH$AUC
AUCkch[,2] <- resKCH$CI_AUC_low
AUCkch[,3] <- resKCH$CI_AUC_upp
row.names(AUCkch)  = c('Allenbach', 'Xie', 'Zhang1', 'Zhang2')

### Gupta results
###--------------

AUCgupta <- matrix(NA, 4, 3)
AUCgupta[1,] <- c(0.76, 0.69, 0.82)
AUCgupta[2,] <- c(0.7, 0.65, 0.76)
AUCgupta[3,] <- c(0.74, 0.69, 0.79)
row.names(AUCgupta) <- row_names


### Development cohort results
###---------------------------

AUCdev <- matrix(NA, 4, 3)
AUCdev[1,] <- c(0.89, 0.86, 0.93)
AUCdev[2,] <- c(0.91, NA, NA)
AUCdev[3,] <- c(0.88, NA, NA)
AUCdev[4,] <- c(0.79, NA, NA)
row.names(AUCdev) <- row_names

############# Set new row order
new_row_order = c('Xie', 'Zhang1', 'Allenbach', 'Zhang2')
new_print_names = c('\n\nXie\nmortality', '\n\n\nZhang\nmortality', '\n\n\nAllenbach\npoor outcome', '\n\n\nZhang\npoor outcome')

AUCoslo = AUCoslo[new_row_order, ]
AUCkch = AUCkch[new_row_order, ]
AUCdev = AUCdev[new_row_order, ]
AUCgupta = AUCgupta[new_row_order, ]
#############


## Barplot
##--------
mybars <- barplot(height = rbind(AUCoslo[,1], AUCkch[,1], AUCdev[,1], AUCgupta[,1]), beside = TRUE, plot = FALSE)

 png('barplot_model_cohort_comparison.png', height = 2400, width = 3200, res=300)

par(mar=c(5.1, 5.1, 4.1, 0.1))

par(mgp=c(3,2.5,0))
barplot(height = rbind(AUCoslo[,1], AUCkch[,1], AUCdev[,1], AUCgupta[,1]), beside = TRUE,
        names.arg = new_print_names,
        col=c('orange', 'forestgreen', 'purple', 'turquoise'),
         ylim=c(0,1.0), cex.axis=1.5, cex.names=1.6, cex.lab=1.5)

segments(x0 = as.vector(mybars), x1 = as.vector(mybars), 
         y0 = as.vector(rbind(AUCoslo[,2], AUCkch[,2], AUCdev[,2], AUCgupta[,2])),
         y1 = as.vector(rbind(AUCoslo[,3], AUCkch[,3], AUCdev[,3], AUCgupta[,3])),
         lwd=2) 
dev.off()
